"""This module holds various plotting classes."""
from typing import Any

import pandas as pd
import os
import plotly.express as px
import plotly.graph_objects as go
import vtk
from vtk.util.numpy_support import vtk_to_numpy
import plotly.io as pio


class _PlotlyPlot:
    """Base class for plotting classes based on plotly.

    Defines common methods to handle plotly plots.
    """

    # Default layout for plots generated by plotly
    _DEFAULT_LAYOUT: dict[str, Any] = {
        "plot_bgcolor": "rgba(0, 0, 0, 0)",
        "paper_bgcolor": "rgba(0, 0, 0, 0)",
        "template": "plotly_dark",
    }

    def __init__(self, **kwargs: str) -> None:
        """Create a new _PlotlyPlot instance."""
        self._fig = go.Figure()
        self._layout: dict[str, Any] = self._DEFAULT_LAYOUT.copy()
        self._fig.update_layout(**self._layout)
        self.configure(**kwargs)  # type: ignore

    def to_html(self) -> str:
        """Export plot as an html encoded string.

        Returns:
            html_fig: Plotly figure in html format.
        """
        self._fig.update_layout(**self._layout)
        return self._fig.to_html(
            include_plotlyjs="cdn", include_mathjax="cdn", full_html=False
        )

    def to_image_file(self, path: str) -> None:
        """Export plot as image file.

        Supported formats png, jpg, jpeg, webp, svg, pdf, eps.

        Args:
            path: Target path for image.
        """
        self._fig.update_layout(**self._layout)
        self._fig.write_image(path)

    def configure(
        self,
        title: str = None,
        xlabel: str = None,
        ylabel: str = None,
        legend_title: str = None,
        width: int = None,
        height: int = None,
    ) -> None:
        """Set various configurations for the plot.

        Args:
            title: Figure title.
            xlabel: Label of the x-axis.
            ylabel: Label of the y-axis.
            legend_title: Title of the legend.
            width: Width of the figure.
            height: Height of the figure.
        """
        if title is not None:
            self._layout["title"] = title
        if xlabel is not None:
            self._layout["xaxis_title"] = xlabel
        if ylabel is not None:
            self._layout["yaxis_title"] = ylabel
        if legend_title is not None:
            self._layout["legend_title"] = legend_title
        if width is not None:
            self._layout["width"] = width
        if height is not None:
            self._layout["height"] = height


class LinePlot(_PlotlyPlot):
    """Line plot."""

    def __init__(
        self,
        dataframe: pd.DataFrame,
        x: str = None,
        y: str = None,
        name: str = None,
        color: str = None,
        **kwargs: str,
    ) -> None:
        """Create a new LinePlot instance.

        Args:
            dataframe: The dataframe to plot.
            x: Label of the dataframe to use for the x-axis.
            y: Label of the dataframe to use for the y-axis.
            color: Label of the dataframe to use for the color.
        """
        super().__init__(**kwargs)
        self._fig.add_trace(
            go.Scatter(
                name=name,
                x=dataframe[x],
                y=dataframe[y],
                mode="lines",
                line=dict(color="rgba(99, 110, 250, 0.5)"),
                showlegend=False,
            )
        )

    def add_trace(
        self,
        dataframe: pd.DataFrame,
        x: str = None,
        y: str = None,
        name=None,
    ):
        self._fig.add_trace(
            go.Scatter(
                name=name,
                x=dataframe[x],
                y=dataframe[y],
                mode="lines",
                line=dict(color="rgba(99, 110, 250, 0.5)"),
                showlegend=False,
            )
        )


class LinePlotWithUpperLower(_PlotlyPlot):
    """Line plot with error bars between upper and lower."""

    def __init__(
        self,
        dataframe_mean: pd.DataFrame,
        dataframe_upper: pd.DataFrame,
        dataframe_lower: pd.DataFrame,
        x: str = None,
        y: str = None,
        **kwargs: str,
    ) -> None:
        """Create a new LinePlotWithUpperLower instance.

        Args:
            dataframe_mean: The dataframe for the center line.
            dataframe_upper: The dataframe for the upper line.
            dataframe_lower: The dataframe for the lower line.
            x: Label of the dataframe to use for the x-axis.
            y: Label of the dataframe to use for the y-axis.
        """
        super().__init__(**kwargs)

        # print(pio.templates["plotly_dark"])
        # colors= [#636efa, #EF553B, #00cc96, #ab63fa, #FFA15A, #19d3f3, #FF6692, #B6E880, #FF97FF, #FECB52],

        self._fig.add_trace(
            go.Scatter(
                name="Mean",
                x=dataframe_mean[x],
                y=dataframe_mean[y],
                mode="lines",
            )
        )
        self._fig.add_trace(
            go.Scatter(
                name="Upper",
                x=dataframe_upper[x],
                y=dataframe_upper[y],
                mode="lines",
                marker=dict(color="#444"),
                line=dict(width=0),
                showlegend=False,
            )
        )
        self._fig.add_trace(
            go.Scatter(
                name="Standard Deviation",
                hovertemplate="%{y}<extra>Lower</extra>",
                x=dataframe_lower[x],
                y=dataframe_lower[y],
                marker=dict(color="#444"),
                line=dict(width=0),
                mode="lines",
                fillcolor="rgba(99, 110, 250, 0.25)",
                fill="tonexty",
            )
        )
        self._fig.update_layout(
            hovermode="x",
        )

    def add_trace(
        self,
        dataframe: pd.DataFrame,
        x: str = None,
        y: str = None,
        name=None,
    ):
        self._fig.add_trace(
            go.Scatter(
                name=name,
                x=dataframe[x],
                y=dataframe[y],
                mode="lines",
                line=dict(color="#FFA15A", dash="dash"),
            )
        )


class ViolinPlot(_PlotlyPlot):
    """Violin plot."""

    def __init__(
        self,
        dataframe: pd.DataFrame,
        x: str = None,
        y: str = None,
        color: str = None,
        **kwargs: str,
    ) -> None:
        """Create a new ViolinPlot instance.

        Args:
            dataframe: The dataframe to plot.
            x: Label of the dataframe to use for the x-axis.
            y: Label of the dataframe to use for the y-axis.
            color: Label of the dataframe to use for the color.
        """
        super().__init__(**kwargs)
        for col in dataframe.columns:
            self._fig.add_trace(
                go.Violin(
                    y=dataframe[col],
                    name=col,
                    points="all",
                    jitter=0.05,
                    box_visible=True,
                    meanline_visible=True,
                )
            )

    def add_lines(
        self,
        x: list[str],
        y: list[float],
        name=None,
    ):
        self._fig.add_trace(
            go.Scatter(
                x=x,
                y=y,
                mode="markers",
                marker_symbol=41,
                marker_line_color="#FFA15A",
                marker_color="#FFA15A",
                marker_line_width=2,
                marker_size=40,
                name=name,
            )
        )


class TablePlot(_PlotlyPlot):
    """Table plot."""

    def __init__(self, dataframe: pd.DataFrame, **kwargs: str):
        """Create a new TablePlot instance.

        Args:
            dataframe: The dataframe to plot.
        """
        super().__init__(**kwargs)
        columns = list(dataframe.columns)
        table = go.Table(
            header=dict(
                values=columns,
                line_color="white",
                fill_color="rgba(0,0,0,0)",
                font=dict(color="white"),
            ),
            cells=dict(
                values=[dataframe[col] for col in columns],
                line_color="white",
                fill_color="rgba(0,0,0,0)",
                font=dict(color="white"),
            ),
        )
        self._fig = go.Figure(data=[table])


class Vtk3dPlot(_PlotlyPlot):
    """3d plot from vtk file."""

    def __init__(self, filename: str, color: str = None, **kwargs: str):
        """Create a new Vtk3dPlot instance.

        Args:
            filename: Name of the vtk file to plot.
            color: Color of the mesh.
        """
        super().__init__(**kwargs)

        if not os.path.exists(filename):
            raise FileNotFoundError(
                f"Could not plot {filename}. The specified file does not exist."
            )

        camera = dict(eye=dict(x=2, y=2, z=0.1))

        self._layout.update({"hovermode": False, "scene_camera": camera})

        # Setup vtk reader
        if filename.endswith(".vtp"):
            reader = vtk.vtkXMLPolyDataReader()
            reader.SetFileName(filename)
            reader.Update()
            polydata = reader.GetOutput()
        else:
            raise NotImplementedError("Filetype not supported.")

        # Extract mesh
        points = vtk_to_numpy(polydata.GetPoints().GetData())
        cells = vtk_to_numpy(polydata.GetPolys().GetData()).reshape(-1, 4)
        x, y, z = points[:, 0], points[:, 1], points[:, 2]
        i, j, k = cells[:, 1], cells[:, 2], cells[:, 3]

        mesh_args = {}
        if color is not None:
            mesh_args["color"] = color
        self._fig = go.Figure(
            data=[go.Mesh3d(x=x, y=y, z=z, i=i, j=j, k=k, **mesh_args)],
        )
        self._fig.update_scenes(
            xaxis_visible=False, yaxis_visible=False, zaxis_visible=False
        )
